### ISSUE TITLE
Attachments don't work

### ISSUE THREAD

**Issue by turkeyphant** [genetrader/pushbullet-fix#1]
Either by dropping files/images or using the paperclip icon. Nothing pushes other than text.

Also a small bug in that when you use the paperclip and nothing sends, afterwards text pushes do not display in the popup (although they are sent) until you reopen it.

**Comment by genetrader** [comment]
This was fixed in a previous build.  Try the latest release - this is working.

**Comment by turkeyphant** [comment]
> This was fixed in a previous build. Try the latest release - this is working.

Latest release from 2 months ago? Still not working on my end. e.g. images show as sent in extension pop up but don't show on web or other devices.

**Comment by genetrader** [comment]
This has been updated quite a bit.  Did you try using this version - it is as of a few days ago:  

https://github.com/genetrader/pushbullet-fix/archive/refs/tags/2.0.zip

If yes, can you tell me the browser you are using so I can troubleshoot it?  Thanks.

**Comment by genetrader** [comment]
Sorry, reopened this issue for you to report either way.  I'll get this fixed if this new version doesn't work for you.  The issues you described were fixed, however, about 2 weeks ago but I'll wait to confirm with you.  Thank you for the feedback.

**Comment by genetrader** [comment]
You should get latest release from here and it will alert you to updates
under settings area:


https://github.com/genetrader/pushbullet-fix

and here you can directly download the current latest version:

https://github.com/genetrader/pushbullet-fix/releases/download/v379/pushbullet-v379-final.zip

All the best,

Gene Waxman
